### ISSUE TITLE
Peer Review 1

### ISSUE THREAD

**Issue by jpdhmc** [pgfrank1/MovieTVShowWatchList#3]
@pawaitemadisoncollege

# Design/Code Review 1

## Project:
Java Movie Database
### Developer:
Patrick Frank
### Reviewer:
John Den Hartog
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|The problem statement is clear and it's a great idea for an application! The average person may not understand what an API is, so maybe that wording could be changed. The final sentence feels a little bit unrelated to the idea of the problem statement, which is more focused on knowing what your friends are watching as opposed to being a trend setter.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |The UI designs look great. The site looks easy to navigate and I like the idea of being able to filter between watched/planned/on hold/dropped. It might be cool to have movie cards expand on mouseover with a short summary/details. Maybe have a section on the homepage to show a feed of the most recent movies your friends have watched?|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|The database model looks flawless to me. I don't see anything missing, and the relationships seem well thought out.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.|The project structure looks solid. The DAOs do seem to have a bit of repeated code - I haven't refactored my DAOs myself, but Paula has alluded to rewriting those classes to try and eliminate some of the redundancies. Logging statements are being used and I see test classes have been written for the UserDao and UserMovieDao. I think this project is on the right track!|

**Comment by pawaitemadisoncollege** [comment]
Thanks @jpdhmc for your careful review including both kudos and areas for possible improvement. 

You mentioned that DAO refactoring, so I thought I'd share the link to the generic dao with both of you - you can feel free to use this as is or tweak as you see fit. https://github.com/mad-ent-java-s23/FatBikeTrailReports/blob/main/src/main/java/com/paulawaite/fbtr/persistence/GenericDao.java

This project also has the opportunity to use logging here: 
![Screen Shot 2023-03-08 at 3 54 36 PM](https://user-images.githubusercontent.com/13874466/223859351-02b08429-1632-4337-8e57-c64505d612cf.png)
